#On Windows, the config file should be located at:
#  %APPDATA%\alacritty\alacritty.toml

shell.program = "C:\\WINDOWS\\system32\\wsl.exe"
shell.args = ["-d Archlinux", "--cd ~/repo/"]

[window]
title = "Alacritty"
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.99

[scrolling]

[cursor]
style = "Underline"

[terminal]
osc52 = "CopyPaste"

[font]
normal = {family = "0xProto Nerd Font"}
size = 10.0
